# Generated by Django 4.2.7 on 2023-12-04 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=100)),
                ('trade_code', models.TextField(max_length=100)),
                ('high', models.DecimalField(decimal_places=3, max_digits=10)),
                ('low', models.DecimalField(decimal_places=3, max_digits=10)),
                ('open', models.DecimalField(decimal_places=3, max_digits=10)),
                ('close', models.DecimalField(decimal_places=3, max_digits=10)),
                ('volume', models.BigIntegerField()),
            ],
        ),
    ]
