# Generated by Django 4.2.7 on 2023-12-07 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='close',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='data',
            name='date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='data',
            name='high',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='data',
            name='low',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='data',
            name='open',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='data',
            name='trade_code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='data',
            name='volume',
            field=models.CharField(max_length=100),
        ),
    ]
